### ISSUE TITLE
Add a Preview on the MJML Template form

### ISSUE THREAD

**Issue by jacebenson** [MBahrSNC/mega#17]
I get we can do this from the email but this could save some clicks and would be useful.

**Comment by jacebenson** [comment]
The beginning of this is done. We really need to get the ui actions client scripts to make sense.

**Comment by MBahrSNC** [comment]
I wonder if splitting the form layout with the preview makes sense.

**Comment by jacebenson** [comment]
We had a preview on the template.  Can we close this?
